#@TYPE: Machine
#@NAME: amd-cortexa53-common
#@DESCRIPTION: Common AMD machine used to build a shared root filesystem for Cortex-A53 boards without a Mali-400 GPU (e.g. Zynq UltraScale+ MPSoC CG/DR variants). Not bootable on its own.

#### Preamble
MACHINEOVERRIDES =. "${@['', 'amd-cortexa53-common:']['amd-cortexa53-common' != '${MACHINE}']}"
#### Regular settings follow

DEFAULTTUNE = "cortexa72-cortexa53"

# These devices are all zynqmp related
require conf/machine/zynqmp-generic.conf

# We do not want the boot.bin, bootloader and other pre-Linux things to build,
# these should come from the machine
HW_BOOT_MODE = ""
SOC_ON_DISK_BOOT_BIN = ""
EXTRA_IMAGEDEPENDS = "qemu-devicetrees-native"
IMAGE_BOOT_FILES = ""
IMAGE_EFI_BOOT_FILES = ""

# Clear serial consoles, use the kernel console=
SERIAL_CONSOLES = ""

# Clear the machine specifc settings
QB_CMDLINE_IP_SLIRP = ""
QB_CMDLINE_IP_TAP = ""
QB_DEFAULT_KERNEL = ""
QB_DTB = ""
QB_MACHINE = ""
QB_MEM = ""
QB_NETWORK_DEVICE = ""
QB_NO_PNI = ""
QB_OPT_APPEND = ""
QB_ROOTFS_OPT = ""
QB_SERIAL_OPT = ""

MACHINE_FEATURES += "rfsoc fpga-overlay efi usbgadget wifi"

ENABLE_TSN = "1"
#### No additional settings should be after the Postamble
#### Postamble
PACKAGE_EXTRA_ARCHS:append = "${@['', ' amd_cortexa53_common']['amd-cortexa53-common' != "${MACHINE}"]}"
