#@TYPE: Machine
#@NAME: amd-rv64imafdc-zicbom-zba-zbb-zbs-common
#@DESCRIPTION: Common AMD machine used to build a shared 64-bit RISC-V root filesystem (rv64imafdc with Zicbom/Zicsr/Zifencei/Zba/Zbb/Zbs extensions) for MicroBlaze-V soft-processor boards. Not bootable on its own.

#### Preamble
MACHINEOVERRIDES =. "${@['', 'amd-rv64imafdc-zicbom-zba-zbb-zbs-common:']['amd-rv64imafdc-zicbom-zba-zbb-zbs-common' != '${MACHINE}']}"
#### Regular settings follow

# Set the default for a modern full feature (32-bit) microblaze-v...
# Note, glibc does not support 'f' without 'd'
TUNE_FEATURES:tune-microblaze-v = "${@mbv.tune.riscv_isa_to_tune("rv64imafdc_zicbom_zicsr_zifencei_zba_zbb_zbs")}"

# These devices are all zynqmp related
require conf/machine/microblaze-v-generic.conf

# We do not want the boot.bin, bootloader and other pre-Linux things to build,
# these should come from the machine
HW_BOOT_MODE = ""
SOC_ON_DISK_BOOT_BIN = ""
EXTRA_IMAGEDEPENDS = "qemu-devicetrees-native"
IMAGE_BOOT_FILES = ""
IMAGE_EFI_BOOT_FILES = ""

# Clear serial consoles, use the kernel console=
#SERIAL_CONSOLES = ""

# Clear the machine specifc settings
#QB_CMDLINE_IP_SLIRP = ""
#QB_CMDLINE_IP_TAP = ""
#QB_DEFAULT_KERNEL = ""
#QB_DTB = ""
#QB_MACHINE = ""
#QB_MEM = ""
#QB_NETWORK_DEVICE = ""
#QB_NO_PNI = ""
#QB_OPT_APPEND = ""
#QB_ROOTFS_OPT = ""
#QB_SERIAL_OPT = ""

# Might want to add EFI or fpga-overlay, TBD
MACHINE_FEATURES += ""

#### No additional settings should be after the Postamble
#### Postamble
PACKAGE_EXTRA_ARCHS:append = "${@['', ' amd_rv64imafdc_zicbom_zba_zbb_zbs_common']['amd-rv64imafdc-zicbom-zba-zbb-zbs-common' != "${MACHINE}"]}"
