# We have a conf and classes directory, add to BBPATH.
BBPATH .= ":${LAYERDIR}"

# Add recipes and recipe append files to BitBake's search path.
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "ebaz4205"
BBFILE_PATTERN_ebaz4205 = "^${LAYERDIR}/"
BBFILE_PRIORITY_ebaz4205 = "7"

LAYERSUMMARY_ebaz4205 = "Ebang EBAZ4205 Zynq-7000 BSP"
LAYERDESCRIPTION_ebaz4205 = "Board support for the Ebang EBAZ4205, including SD boot through U-Boot SPL."

LAYERDEPENDS_ebaz4205 = "core xilinx"
LAYERSERIES_COMPAT_ebaz4205 = "scarthgap"
