# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "amd-adaptive-socs-core"
BBFILE_PATTERN_amd-adaptive-socs-core = "^${LAYERDIR}/"
# Currently no files, so set an empty pattern means ignore the error
BBFILE_PATTERN_IGNORE_EMPTY_amd-adaptive-socs-core = "1"
BBFILE_PRIORITY_amd-adaptive-socs-core = "6"

LAYERSUMMARY_amd-adaptive-socs-core = "AMD adaptive SoC core recipes \
and classes"
LAYERDESCRIPTION_amd-adaptive-socs-core = "Core layer for AMD Adaptive \
SoC support: bbclasses, includes, and recipes shared across the BSP \
and reference distros for Versal, Zynq UltraScale+, Zynq-7000, and \
MicroBlaze-V targets."

LAYERDEPENDS_amd-adaptive-socs-core = "\
    core \
    xilinx \
    xilinx-standalone \
    xilinx-standalone-sdt \
    xilinx-microblaze \
    "

LAYERRECOMMENDS_amd-adaptive-socs-core = "\
     openamp-layer \
     "

LAYERSERIES_COMPAT_amd-adaptive-socs-core = "scarthgap"
