# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# TO override a oe-core bbclass
BBPATH =. "${LAYERDIR}/oe-core/meta:"

# We have recipes-* directories, add to BBFILES
BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
    "

BBFILE_COLLECTIONS += "amd-edf"
BBFILE_PRIORITY_amd-edf = "5"

LAYERSUMMARY_amd-edf = "AMD Embedded Development Framework reference \
distro"
LAYERDESCRIPTION_amd-edf = "Distribution layer providing the amd-edf \
and amd-edf-small distros, image recipes, packagegroups, and SDK \
helpers that make up the AMD Embedded Development Framework reference \
platform."
BBFILE_PATTERN_amd-edf = "^${LAYERDIR}/"
BBFILE_PATTERN_IGNORE_EMPTY_amd-edf = "1"

LAYERDEPENDS_amd-edf = "\
    core \
    xilinx \
    xilinx-standalone \
    xilinx-standalone-sdt \
    xilinx-microblaze \
    xilinx-demos \
    meta-xilinx-imgrcry \
    amd-adaptive-socs-core \
    amd-adaptive-socs-bsp \
    ros2-layer \
    ros2-jazzy-layer \
    openamp-layer \
    xilinx-virtualization \
    virtualization-layer \
    security \
    tpm-layer \
    qt5-layer \
    "

LAYERSERIES_COMPAT_amd-edf = "scarthgap"

LAYERRECOMMENDS_amd-edf = "kria"

LAYERBASE_amd-edf = "${LAYERDIR}"
AMD-EDF_OECORE = "${LAYERBASE_amd-edf}/oe-core"

BBFILES_DYNAMIC += " \
    xilinx-mali400:${LAYERDIR}/dynamic-layers/xilinx-mali400/recipes-*/*/*.bb \
    xilinx-mali400:${LAYERDIR}/dynamic-layers/xilinx-mali400/recipes-*/*/*.bbappend \
    xilinx-virtualization:${LAYERDIR}/dynamic-layers/xilinx-virtualization/recipes-*/*/*.bbappend \
    kria:${LAYERDIR}/dynamic-layers/kria/recipes-*/*/*.bb \
    kria:${LAYERDIR}/dynamic-layers/kria/recipes-*/*/*.bbappend \
    "

USER_CLASSES += "amd-edf-check-image"
