# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "amd-adaptive-socs-bsp"
BBFILE_PATTERN_amd-adaptive-socs-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_amd-adaptive-socs-bsp = "6"

LAYERSUMMARY_amd-adaptive-socs-bsp = "AMD adaptive SoC BSP machine \
configurations"
LAYERDESCRIPTION_amd-adaptive-socs-bsp = "Board support package layer \
providing machine .conf, machine YAML, and device-tree assets for AMD \
Versal, Versal Gen 2, Zynq UltraScale+ MPSoC/RFSoC, Zynq-7000, and \
MicroBlaze-V evaluation kits and SOM/carrier combinations."

BBFILES_DYNAMIC += " \
amd-edf:${LAYERDIR}/dynamic-layers/meta-amd-edf/recipes-*/*/*.bb \
amd-edf:${LAYERDIR}/dynamic-layers/meta-amd-edf/recipes-*/*/*.bbappend \
meta-xilinx-imgrcry:${LAYERDIR}/dynamic-layers/meta-xilinx-imgrcvry/recipes-*/*/*.bb \
meta-xilinx-imgrcry:${LAYERDIR}/dynamic-layers/meta-xilinx-imgrcvry/recipes-*/*/*.bbappend \
xilinx-standalone-sdt:${LAYERDIR}/dynamic-layers/xilinx-standalone-sdt/recipes-*/*/*.bb \
xilinx-standalone-sdt:${LAYERDIR}/dynamic-layers/xilinx-standalone-sdt/recipes-*/*/*.bbappend \
"

LAYERDEPENDS_amd-adaptive-socs-bsp = "\
    core \
    xilinx \
    xilinx-standalone \
    xilinx-standalone-sdt \
    xilinx-microblaze \
    xilinx-multimedia \
    "

LAYERRECOMMENDS_amd-adaptive-socs-bsp = "\
    amd-adaptive-socs-core \
    openamp-layer \
    xilinx-virtualization \
    virtualization-layer \
    security \
    tpm-layer \
    "

LAYERSERIES_COMPAT_amd-adaptive-socs-bsp = "scarthgap"

# We need to set sdtgen dts and pdi path in machine conf files instead of
# hardcoded path which was generated during gen-machine-conf sdt processing.
BSPLAYERDIR_amd-adaptive-socs-bsp = "${LAYERDIR}"
