require conf/distro/amd-edf.conf

DISTRO = "amd-edf-small"
DISTRO_NAME = "AMD Embedded Development Framework (Small) Linux distribution"

# Based on poky
DISTROOVERRIDES = "poky:amd-edf:amd-edf-small"

# Default to sysvinit
POKY_INIT_MANAGER:amd-edf-small = "sysvinit"

POKY_DEFAULT_DISTRO_FEATURES:amd-edf-small = ""

#Small does not support mulitarch, security or virtualization like amd-edf does.
AMD-EDF_DISTRO_FEATURES:amd-edf-small = ""

AMD-EDF_DISTRO_FEATURES:amd-edf-small:append:aarch64 = " \
    openamp \
    efi \
    "

# Stop packagegroup-core-boot from including bootbin, device-tree and kernel to /boot
MACHINE_ESSENTIAL_EXTRA_RDEPENDS:pn-packagegroup-core-boot = ""

# Instead include that software into a standard rootfs
ROOTFS_BOOTSTRAP_INSTALL:append = " ${MACHINE_ESSENTIAL_EXTRA_RDEPENDS}"

# For a smaller system, we want smaller kernels
# Switch the KERNEL_IMAGETYPE to compressed
DEFAULT_KERNEL_IMAGETYPE := "${KERNEL_IMAGETYPE}"
DEFAULT_KERNEL_IMAGETYPE:arm = "uImage"
DEFAULT_KERNEL_IMAGETYPE:aarch64 = "Image.lzma"

KERNEL_IMAGETYPES += "${DEFAULT_KERNEL_IMAGETYPE}"
KERNEL_IMAGETYPE = "${DEFAULT_KERNEL_IMAGETYPE}"

# Switch to small kernel
PREFERRED_PROVIDER_virtual/kernel:zynqmp = "linux-xlnx-small"
PREFERRED_PROVIDER_virtual/kernel:versal = "linux-xlnx-small"
PREFERRED_PROVIDER_virtual/kernel:versal-net = "linux-xlnx-small"
PREFERRED_PROVIDER_virtual/kernel:versal-2ve-2vm = "linux-xlnx-small"

# Enable busybox
PREFERRED_PROVIDER_base-utils = "busybox"
VIRTUAL-RUNTIME_base-utils = "busybox"
VIRTUAL-RUNTIME_base-utils-hwclock = "busybox-hwclock"
VIRTUAL-RUNTIME_base-utils-syslog = "busybox-syslog"
